declare module 'react-router-dom'
declare module 'react-router'
declare module 'marked'
declare module 'prismjs'
declare module 'uuid/v4'
declare module 'react-transition-group'
declare module 'react-transition-group/TransitionGroup'
